# Lenguaje del código
language: ruby

# Versiones de ruby donde se va a probar
rvm:
    - 2.2.9

# Instalamos última versión de bundle
before_install:
    - gem install bundle

install: bundle install

# Para ejecutar los test 
script: rake test