name: auto-docker-build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: login en GitHub Container Registry
        - uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.TOK }}
        - name: construccion de la imagen
          run: docker build -t ghcr.io/joseegc10/env-get-match:latest .
        - name: ejecutar tests
          run: docker run -t -v `pwd`:/test ghcr.io/joseegc10/env-get-match:latest
        - name: push a GitHub Container Registry
          run: docker push ghcr.io/joseegc10/env-get-match:latest